name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set image tag based on commit SHA
        run: echo "IMAGE_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
        
      - name Logout from Docker Hub
        run: docker logout

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build frontend
        run: docker build -t cyberfrogg/assetsproxy-frontend:latest -f ./assets-proxy-frontend/Dockerfile ./assets-proxy-frontend/
        
      - name: Build backend
        run: docker build -t cyberfrogg/assetsproxy-backend:latest -f ./assets-proxy-backend/Dockerfile ./assets-proxy-backend/

      - name: Push Docker images
        run: |
          sudo docker push cyberfrogg/assetsproxy-frontend:latest
          sudo docker push cyberfrogg/assetsproxy-backend:latest
